<aside class="sidebar" ng-app="AdminApp" ng-controller="AdminController">
    <ul>
        <li class="tab" data-file="monitoring.phtml">Pregled
            <ul class="activeul">
                <li id='active' class="1" data-file="monitoring.phtml">Monitoring</li>
                <li data-file="statistic.phtml">Statistika</li>
            </ul>
        </li>
        <li class="tab" data-file="users.phtml">Uređuj korisnike
            <ul class="nonactiveul">
                <li data-file="users.phtml">Korisnici</li>
                <li data-file="addusers.phtml">Dodaj korisnika</li>
            </ul>
        </li>
        <li class="tab" data-file="cars.phtml">Uređuj automobile
            <ul class="nonactiveul">
                <li data-file="cars.phtml">Automobili</li>
                <li data-file="addcars.phtml">Dodaj automobile</li>
            </ul>
        </li>
        <li class="tab" data-file="content.phtml">Uređuj sadržaj</li>
        <li class="tab" data-file="info.phtml">Informaicje</li>
    </ul>
</aside>
<main class="main"">

</main>

