<!DOCTYPE html>
<html lang="sr">
<head>
    <title>Rent a car - application</title>
    <meta charset="utf-8">
    <meta name="description" content="application for rent a car">
    <link rel="stylesheet" href="asset/css/style.css" type="text/css" media="screen" />
    <script src="https://kit.fontawesome.com/dd9d49e9ef.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,400;0,500;0,600;0,700;1,100;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
</head>
<body>
<?php
include_once 'includes/header.phtml';
include_once 'includes/navbar.phtml';
include_once 'includes/frontimage.phtml';
include_once 'functions/Functions.php';
?>
<div class="wrapper">
    <h2>Izaberite automobile:</h2>
    <section class="cars">
        <?php
        if($cars==null){
            echo '<p> Nema unetih automobila! </p>';
        }else{
            foreach ($cars as $car){
                echo "<article class='car'>
                <h1>{$car['brand_name']} {$car['model']}</h1>";
                $imagecar=selectImageCar($car['image']);
                echo "<img src='asset/img/cars/{$imagecar}' alt='Nema slike!'>
                <p>Na stanju: {$car['availble']}</p>
                <div class='price'><p><b>Cena:</b></p>
                <p>24 časa: {$car['24h']}</p>
                <p>48 časa: {$car['48h']}</p>
                <p>72 časa: {$car['72h']}</p></div>
                
                <div class='rentbutton'>
                <a href='?rent&car_id={$car['id']}'>Iznajmi</a>
                </div>";
            }
        }

        ?>
    </section>
    <section class="aboutus">
        <p>ovo je div gde ce pisati informacije o nasoj firmi</p>
    </section>
    <footer class="footer">
        <p>Rent a car application 2020 &copy; by Srdjan Radosavljevic </p>
    </footer>
</div>
