<img src="../asset/img/logo-speed.png">
<h3>Unesite e-poštu za resetovanje naloga</h3>
<form action="#" method="post">
    <label for="username">
        <i class="fas fa-user"></i>
    </label>
    <input type="text" name="email" placeholder="Unesite e-poštu" id="username" required>
    <br><br>
    <input type="submit" value="Pošalji">
    <br>
    <div class="message"><?= $message ?></div>
</form>

<div class="buttonforlogin">
    <a href="index.php"><i class="fas fa-arrow-left"></i></a>
</div>